umccr/libica

Makefile, swagger/gds.json, swagger/tes.json, swagger/wes.json, syncapi.sh
* Added swagger validate and check target
=> Updated ICA OpenAPI definition 20210308

package.json, yarn.lock
* Mitigated dependabot security alerts
=> Bumped dev tools in node npm packages

.gitignore, Makefile, libica/app/__init__.py, libica/app/gds.py, libica/app/wes.py, setup.py, tests/app/__init__.py, tests/app/test_gds.py, tests/app/test_ica.py, tests/app/test_wes.py, tox.ini
* Ported Portal utils ica, wes, gds impls
* Excluded tests from distro
* Added tox
=> Added app package for reusable impls

README.md, package.json, yarn.lock
* Refactored to devDependencies
* Removed `prism-cli` as using it through Docker
=> Bumped dev tools dependencies

swagger/openapi_public.yaml
* Upstream Release "07 June 2022 - ICA v2.6.0 and CLI v2.3.0"
https://help.ica.illumina.com/reference/r-releasenotes
=> Updated ICAv2 OpenAPI definition 20220609

libica/app/__init__.py, libica/app/dataops.py, libica/app/gds.py, libica/app/projectops.py, pilot.py, pilotapp.py, tests/app/test_dataops.py
* Implemented ICAv2 data URI scheme
https://github.com/umccr-illumina/ica_v2/issues/96
* Refactored dataops module and ProjectDataOps
* Added get files by suffix method to gds module
* Improved test and pilot code
=> Improved app implementations

.github/workflows/prbuild.yml, Makefile, README.md, openapi/docs/app/README.md, openapi/docs/index.md, openapi/mkdocs.yml, setup.py
* Bumped version 2.1.0rc1
* Added Python 3.10 support
=> Updated doc and settings

CHANGELOG.md, setup.py
* See https://github.com/umccr-illumina/libica/milestone/6?closed=1
=> Release 2.1.0

setup.py, swagger/ens.json, swagger/gds.json, swagger/tes.json, swagger/wes.json
* Also bumped version next 2.2.0rc1
=> Updated ICAv1 Swagger definition 20230216

libica/openapi/v2/api_client.py, libica/openapi/v2/configuration.py
=> Added support for POST form field filename settable

examples/create_cwl_pipeline.py, examples/gds_app_script.py, examples/gds_list_files.py, examples/tabix-workflow__0.2.6__1677025399/params.xml, examples/tabix-workflow__0.2.6__1677025399/tools/tabix/0.2.6/tabix__0.2.6.cwl, examples/tabix-workflow__0.2.6__1677025399/workflow.cwl, libica/app/gds.py
* Minor refactor gds examples
Related #74
=> Added ICA v2 create CWL pipeline example using tabix workflow

setup.py
* See https://github.com/umccr-illumina/libica/milestone/7?closed=1
=> Release 2.2.0

examples/gds_app_script.py, examples/gds_gen_presigned_with_temp_cred.py, libica/app/gds.py, tests/app/test_gds.py
* Added get file and folder underlay S3 store temp cred
=> Added generating GDS PreSigned URL with override options

CHANGELOG.md, setup.py
* See https://github.com/umccr-illumina/libica/milestone/8?closed=1
=> Release 2.2.1

docker-compose.yml, swagger/gds.json, swagger/openapi_public.yaml, swagger/wes.json
* Added Prism dynamic faker config to control
deterministic return on nextPageToken field
* Fixed Prism image platform
=> Improved ICA endpoint mocking

.gitguardian.yaml, .pre-commit-config.yaml, .secrets.baseline, Makefile, libica/app/__init__.py, libica/openapi/libconsole/configuration.py, libica/openapi/libgds/models/aws_s3_temporary_read_only_credentials.py, libica/openapi/libgds/models/aws_s3_temporary_upload_credentials.py, libica/openapi/libgds/models/object_storage_credentials_response.py, libica/openapi/libgds/models/object_store_settings.py, libica/openapi/libgds/test/test_create_volume_configuration_request.py, libica/openapi/libgds/test/test_object_store_settings.py, libica/openapi/libgds/test/test_update_volume_configuration_request.py, libica/openapi/libgds/test/test_volume_configuration_list_response.py, libica/openapi/libgds/test/test_volume_configuration_response.py, libica/openapi/libtes/models/credentials.py, libica/openapi/v2/api/storage_credentials_api.py, libica/openapi/v2/configuration.py, libica/openapi/v2/model/aws_credentials.py, libica/openapi/v2/model/aws_temp_credentials.py, setup.py
* Added pre-commit hook
* Added detect-secrets and baseline
* Added scanners - ggshield, trufflehog
=> Reinforced DevSecOps

setup.py, swagger/console.json, swagger/gds.json, swagger/tes.json
* Also bumped version next 2.3.0rc1
=> Updated ICAv1 Swagger definition 20231010

CHANGELOG.md, setup.py
* See https://github.com/umccr-illumina/libica/milestone/9?closed=1
=> Release 2.3.0

examples/issue_129.py, libica/openapi/v2/model/settings.py, swagger/openapi_public.yaml
* Made it so that to unblock and fixes #129
=> Fixed discrepancy between API and server backend oneOf vs anyOf

CHANGELOG.md, setup.py
* See https://github.com/umccr-illumina/libica/milestone/10?closed=1
=> Release 2.4.0

examples/issue_135.py, tests/v2/test_issue_135.py
* Also added unit test case
* Resolves #135
=> Added example how to use API request and response endpoint version

README.md, setup.py, tox.ini
=> Added Python3.12 support

CHANGELOG.md, LICENSE, setup.py
* See https://github.com/umccr-illumina/libica/milestone/11?closed=1
=> Release 2.5.0

README.md, examples/issue_138.py
* Added Example section to pointer wrapica and icav2-cli-plugins
* Removed deprecating ICA v1 and App package sections in v3 milestone
=> Updated README

libica/openapi/v3/models/settings.py, openapi/docs/v3/docs/Settings.md
=> Regenerated Settings with anyOf Pydantic construct

tests/v3/hello/workflow.cwl, tests/v3/test_issue_135.py, tests/v3/test_issue_74.py, tests/v3/test_project.py
* Replicated unittest from v2 SDK and setup guard around v3 package usage.
* Added the note about backward compatibility issue where applicable.
=> Added v3 SDK unittest - baseline

swagger/openapi_public.yaml
=> Updated ICA OpenAPI definition 20250605

swagger/openapi_public.yaml
* 2025 June 23 - ICA v2.36.1
https://help.ica.illumina.com/reference/software-release-notes/2025#id-2025-june-23-ica-v2.36.1
=> Updated ICA OpenAPI definition 20250731
